export const inspiration = [
  'An old story told from the island of Kiniwata relates the account of a man known as Johnny Lingo. The youngest and strongest man from the island, Johnny shocked the islanders by paying the father of his bride not the traditional two to three cows for his wife, or even the four to five cows for an exceptional wife. For Sarita, he paid eight. No one could understand: “It would be kindness to call her plain. She was skinny. She walked with her shoulders hunched and her head ducked. She was scared of her own shadow.” Eight cows!? The entire island laughed at the audacity.',
  'Curious about the story, writer Patricia McGerr visited Johnny’s home. She was fascinated by what she describes as the most beautiful woman she’d ever seen. She wrote about this in a Woman’s Day article, “Johnny Lingo and the Eight Cow Wife”: “The lift of her shoulders, the tilt of her chin, the sparkle of her eyes all spelled a pride to which no one could deny her the right.”',
  'When McGerr later pressed Johnny Lingo for his reasoning, he explained, “Many things can change a woman. Things that happen inside, things that happen outside. But the thing that matters most is what she thinks about herself. In Kiniwata, Sarita believed she was worth nothing. Now she knows she is worth more than any other woman in the islands … I wanted an eight-cow wife.”',
  'Now, for obvious reasons, please do not immediately tell your beloved, “Hon, you’re an eight-cow wife.” But remember that, at least in part, a man’s impact may be measured in the joy and character of the people closest to him.',
  'The way that a man sees his wife, the way he cherishes her, has a lasting effect on her beauty within and without. How does your wife feel about you and your relationship to her? How do you want your children to remember your acts of love for their mother?'
]

export const ideas = [
  'One final note: Maybe you are a man who initiates many kindnesses to your wife and you don’t receive much respect or kindness in return. Or perhaps you’re a woman reading this under the burden of a husband who doesn’t serve you or protect you or cherish you. May you be gently, compassionately encouraged: Giving without mutual gain puts you in good company—the company of Jesus. May God give you significant grace as you pray for your husband and encounter the nitty-gritty, everyday battles against resentment and, in many cases, injustice. Our God is the God who sees (Genesis 21:15-21).',
  'Be a student of her. Where do her passions, gifting, and abilities lie? What energizes her? When does she lose track of time because she’s enjoying herself so much? What weights does she bear? (Can you learn incredible things about this woman that even she doesn’t know?)',
  'Ask God for special wisdom in understanding your wife and in loving her well (James 1:5-6).',
  'Make a list of 30 things that you love and/or appreciate about her. Write them on separate sticky notes, and leave one somewhere in the house every day for an entire month.',
  'For what ministry has God created your wife in order to build up His people? Give her time and energy to pursue it.',
  'Take care of the kids for a day so that she can have a personal spiritual retreat to recharge.',
  'Listen to her sincerely: Observe her words, body language, and circumstances in order to compassionately understand her. Make eye contact with her, and ask thoughtful questions, like “How did that affect you?” or basic who/what/where/when/why/how questions.',
  'If she’s got a budding hobby or one that’s been neglected, purchase something small but high-quality that she would enjoy: quality paintbrushes, a beautiful journal, photo software, a top-notch cooking knife, new gloves, athletic equipment (ahem … only if she loves athletics), a well-recommended book on her hobby. Include a note: Just because I love the way you’re made.',
  'Pray with her, and for her, on a regular basis. Consider making it a regular item in your schedule, such as before you leave for work or go to bed.',
  'Compile a CD with songs that specifically encourage things you love about her. Let her know that you intentionally chose these for her and about her.',
  'When circumstances, conversation, or even movies or songs bring up an area in which she excels, lean over and whisper, “You know, you do that so well. I love how you use ___ to bless the people around you.”',
  'Identify the “life-suckers” in her life. What saps her energy? Consider the points of friction that she often faces in her daily routines. Prayerfully ask God to help you see not only what weighs on her, but also how you could help her. Initiate conversation to compassionately find solutions with her. Ask, “What could be done to make that less painful (or less difficult)?”',
  'Gently encourage your children to thank her for different ways she serves them: When they have clean laundry, when she serves dinner, when she drops them off at school. (Make sure you’re modeling consistent gratitude for little things, too.)',
  'Identify your wife’s “love language”—what makes her feel loved and valued. Is it words of affirmation, gifts, physical touch, quality time, or acts of service? She may have more than one. Become fluent in each of her “languages.”',
  'What pleasures in your life do you enjoy that your wife isn’t able to enjoy? She might not be into fishing like you are, for example, but maybe she’d like her own version of alone time. Like you, she might be honored by accolades for her projects well-done, a chance to finish a conversation, or sleeping in on a Saturday.',
  'Allow your wife to set your standard of beauty, and make it clear to her that she is secure: Your eyes are only for her. Enlist the help of a trusted friend or pastor and accountability websites like x3watch.com to develop monogamous eyes that come from a monogamous heart … and a husband she can trust. Security gives way to confidence.',
  'Talk through your budget together with her. Make sure you both have the resources you need to care for your family well. If you primarily manage the budget, ask her to make at least one change before finalizing it. Esteem wise financial decisions she’s made.',
  'Be a student of her body. Ask her, both while you’re in bed and at a completely separate private time, how you can please her sexually and make her feel secure and beautiful. Seek tenderly to understand her past and how it affects her in the bedroom. Be prepared to humbly accept what she says, embracing her without defensiveness.',
  'Gently protect her. Lovingly help her set boundaries with her time, energy, resources, and relationships (kids and mothers-in-law included).',
  'Give her a massage—one that doesn’t lead to sex, unless she’s clear that making love is what she would enjoy most.',
  'Send her an e-mail. Example: “Praying for you today. Thanks for being so courageous in ___.”',
  'Give her one night on a regular basis to do something she loves. Occasionally surprise her with an afternoon “off” so she can do something fun or just be alone.',
  'Consistently mention ways you see her growing to be more like Christ.',
  'Ask her about her “bucket list”—the top things she’d like to do in her lifetime.',
  'Give her a book or audio CD to learn about something she loves doing.',
  'Text her on a stressful day. Example: “REMINDER: I BELIEVE IN U.”',
  'Leave a message on her voicemail: “Thanks for serving our family every day. You are so good at ___.”',
  'Be proactive about doing something together that she really enjoys. Make a date, get her excited, and share her enthusiasm!',
  'Ask her, “If there were one thing I could do to love you better, to really cherish you—and you knew I would listen—what would it be?” Be prepared to follow through.',
  'Tell her areas she’s gifted in. Don’t stretch the truth: Be honest so she can trust you.',
  'Talk with her about setting aside a small part of the budget to pursue the unique ways God has designed her (including her gifts, abilities, and passions)—through education or through sheer enjoyment.',
  'Post on her Facebook wall: “I love being your husband. You still take my breath away.”',
  'Have your children write her notes or letters about what they love about her as a mom.',
  'Ask, “If I could do one thing that would really empower you and inspire you, what would it be?” Listen and follow through.',
  'As you think of them, remind her of specific times when she has made an impact in the lives of others. “Hey, I was thinking the other day about all the times you’ve invested in all those kids who come over here. You do such a good job making people feel welcomed and loved on.” “I don’t think I could count all the meals you’ve brought to people who are sick. You are wonderful at seeing people’s needs and giving of yourself to them.”',
  'Do something fun and unexpected together. Here are a few ideas: play paintball, laser tag, or sand volleyball; organize a picnic and bring the books you’re reading; take photos of each other; play a pickup game of a sport together; go to a drive-in movie, bringing popcorn and her favorite candy (let her initiate any physical advances for this one).',
  'Think about a way you’ve been hurting her or annoying her. Maybe there are ways you’re not “seeing” her—not stepping into her world to understand what it’s like to be her, with all of the things she cares about (see 1 Peter 3:7). Apologize, and work hard at showing true change.',
  'Find a mutually enjoyable activity you like doing together on a regular basis, even if it’s working outside together or playing the Wii together after the kids are in bed.',
  'Create a fun, life-giving atmosphere when you come home.',
  'Design a date night that will help her to de-stress and have fun. (Dare I suggest ballroom dancing lessons?)',
  'What’s difficult about her life right now? Pray for her endurance, and encourage her specifically. Galatians 6:9 is a great start for both. Think, What can I do to ease the load she’s carrying today?',
  'Organize or clean something of yours that you know she finds messy.',
  'Talk with her about her fears—both deep and insignificant. Over time, lead her as you work together to replace those fears with faith in God as expressed in His Word.',
  'Send a snail-mail love note to her at home, affirming all she does for your family.',
  'Think of something on her to-do list that she finds overwhelming or for which she doesn’t have much time. Talk with her (respectfully and gently) about the possibility of having it hired out (maybe you could pay a responsible high school student to log a few hours on housework). Communicate clearly that it’s not because you find her incompetent, but that you want to free her up from a burden.',
  'If your wife likes to dress nicely, go with her to shop for clothes in which she feels confident and looks fantastic.',
  'Be an advocate for her rest. Gently help her to evaluate and set limits on her to-do list, reminding her that she loves others best when she takes time to replenish.',
  'Let her overhear you speaking well of her on the phone—among friends, to your kids, in public places, and to your mother. Tenderly but firmly keep family members from speaking disrespectfully to her or about her.',
  'In her area of weakness, pray about how to subtly, gently step in and help her.',
  'Request, “I’d like you to think about something for me. I’d like you to tell me one area in which you want to challenge me, but you wonder if I will listen and if I’ll receive it well. If you’ll do that, I commit to listen to you without getting defensive or somehow punishing you for telling me.”',
  'If and when she messes up, respond with the kind of grace, compassion, and mercy that God gives us. Respond in a way that communicates, You’re safe with me—and I’m not going to rehash your failures. This is a secure place for you to grow … and I love the journey with you.'
]